//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class todo
    {
        public string Id { get; set; }
        public string task_name { get; set; }
        public long is_complete { get; set; }
    }
}
